on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Assign environment variables
        # This is required because oci requires the repository is lowercase
        run: |
          echo "CHART_REPO=ghcr.io/${OWNER@L}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Get appVersion to insert into chart
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag

      - name: Install Helm
        uses: Azure/setup-helm@v4
        id: install

      - name: Lint Helm chart
        run: helm lint helm/service

      - name: Log in to GitHub Container Registry
        if: github.ref_type == 'tag'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ${{ env.CHART_REPO }} --username ${{ github.repository_owner }} --password-stdin


      - name: Get current Helm chart version
        id: helm_current
        if: github.ref_type == 'tag'
        uses: mikefarah/yq@master
        with:
          cmd: helm show chart helm/service | yq '.version' | cut -d "\"" -f 2

      - name: Get latest Helm chart version
        if: github.ref_type == 'tag'
        id: helm_latest
        uses: mikefarah/yq@master
        with:
          cmd: |-
            # Gets the latest published Helm chart version
            if helm show chart oci://${{ env.CHART_REPO }}/charts/service
            then
              helm show chart oci://${{ env.CHART_REPO }}/charts/service | yq '.version' | cut -d "\"" -f 2
            else
              # This is the first time our Helm chart has been published
              echo "0.0.0"
            fi

      - name: Bump patch version if necessary
        if: github.ref_type == 'tag'
        run: |
          if dpkg --compare-versions ${{ steps.helm_current.outputs.result }} le ${{ steps.helm_latest.outputs.result }}
          then
            # latest is same or after new tag, give it a patch bump
            NEXT=`echo $LATEST | awk -F. -v OFS=. '{$NF += 1 ; print}'` 
          else
            NEXT=${{ steps.helm_current.outputs.result }}
          fi
          echo "CHART_VERSION=$NEXT" >>${GITHUB_ENV}

      - name: Publish Helm chart to container registry
        if: github.ref_type == 'tag'
        run: |
          helm dependencies update helm/service
          helm package helm/service --app-version ${{ steps.meta.outputs.version }} --version ${{ env.CHART_VERSION }} -d /tmp/
          helm push /tmp/helm/service-${{ env.CHART_VERSION }}.tgz oci://${{ env.CHART_REPO }}/charts
